<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="real-estate-Policy-1.0" targetNamespace="urn:com:mist:rews:services:wsdl:RealEstateService">
	<wsdl:documentation>Version: 1.0.1</wsdl:documentation>
	<wsp:Policy wsu:Id="SignAndEncrypt"
		xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
		xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
		wsdl:required="true">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:AsymmetricBinding>
					<wsp:Policy>
						<sp:InitiatorToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:InitiatorToken>
						<sp:RecipientToken>
							<wsp:Policy>
								<sp:X509Token
									sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:RecipientToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<!-- Prefer AES 128. CXF does not support multiple algorithm suites -->
								<sp:Basic128Rsa15 />
								<!--<sp:Basic256Rsa15 />-->
								<!--<sp:TripleDesRsa15 />-->
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<!--<sp:IncludeTimestamp />-->
						<sp:EncryptSignature />
						<sp:OnlySignEntireHeadersAndBody />
					</wsp:Policy>
				</sp:AsymmetricBinding>
				<sp:Wss10>
					<wsp:Policy>
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefEmbeddedToken />
					</wsp:Policy>
				</sp:Wss10>
				<sp:Layout>
					<wsp:Policy>
						<sp:Lax />
					</wsp:Policy>
				</sp:Layout>
				<sp:SignedParts>
					<sp:Body />
				</sp:SignedParts>
				<sp:EncryptedParts>
                    <urn:PersonCode xmlns:urn="urn:com:mist:rews:services:xsd:realestate"/>
				</sp:EncryptedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
</wsdl:definitions>
